spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#server:
#  servlet:
#    session:

server:
  port: 443    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。
  ssl:
    key-store-password: 0rrfr00r    #填写jks-password.txt文件内的密码。
    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
    key-store: classpath:www.sgj.cool.jks   #您需要使用实际的证书名称替换domain_name.jks。