spring:
  sql:
    init:
      platform: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/fx_misc;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: Datasource-HikariCPx
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间(ms)
      idle-timeout: 600000
      # 连接池最大连接数
      maximum-pool-size: 100
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期(ms)，值0表示无限生命周期
      max-lifetime: 0
      # 数据库连接超时时间(ms)
      connection-timeout: 1000
      # 连接测试query
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
        matching-strategy: ANT_PATH_MATCHER

#server:
#  servlet:
#    session: